APPLICATION = TinyChirp_DEMO

BOARD ?= microbit-v2

RIOTBASE= $(HOME)/RIOT

WERROR=0

SIMULATE_ADC=0

OUTPUT_RAW_DATA=1

ifneq ($(BOARD), native)
FEATURES_REQUIRED = periph_adc periph_gpio
else
SIMULATE_ADC=1
endif

ifeq ($(SIMULATE_ADC), 1)
CFLAGS += -DSIMULATE_ADC
endif

ifeq ($(OUTPUT_RAW_DATA), 1)
CFLAGS += -DOUTPUT_RAW_DATA
endif

USEMODULE += ztimer
USEMODULE += ztimer_usec

USEMODULE += printf_float
BLOBS += resampled_audio.bin

CFLAGS += -DADC_GAIN=SAADC_CH_CONFIG_GAIN_Gain4
# CFLAGS += -DADC_TACQ=SAADC_CH_CONFIG_TACQ_3us
CFLAGS += -DADC_REF=SAADC_CH_CONFIG_REFSEL_VDD1_4
CFLAGS += -DTHREAD_STACKSIZE_DEFAULT=2048
CFLAGS += -DSTDIO_UART_BAUDRATE=1000000
BAUD = 1000000

include $(RIOTBASE)/Makefile.include
